name: github_notify

on:
  pull_request:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
     - name: discord notify
       env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
       uses: Ilshidur/action-discord@master
       with:
         args: 'The PR {{Event_PAYLOAD.pull_request.id}} for repo {{ EVENT_PAYLOAD.repository.full_name }} has been updated.'
