name: integration-test

on: [pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: get-npm
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: build
      run : |
        npm install -g truffle
        npm install -g
    - name: test
      run: |
        truffle test