name: integration-test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: get-npm
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: dependencies
      run: npm install
    - name: test
      run: CI=true npx truffle test
